### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by czxvan** [suprimpoudel/sakai-nuxt#1]
How to fix or suppress this warning, it's very annoying -.-)
![image](https://github.com/user-attachments/assets/2692cb33-abbe-4a8b-b6de-02a2dc8cfe2a)

**Comment by suprimpoudel** [comment]
Hello @czxvan ,

You can add the following code to your nuxt.config.ts file to silence the deprecation warning:

```
vite: {
  css: {
    preprocessorOptions: {
      scss: {
        silenceDeprecations: ['legacy-js-api'],
      },
    },
  },
}
```

For updates on when this issue will be resolved in Nuxt, you can follow the discussion here: [Issue #30007](https://github.com/nuxt/nuxt/issues/30007).
